language: node_js
node_js:
    - "6"
    - "8"

services:

before_script:
    - chmod ugo-r ./test/data/test-no-perms.log
    - chmod ugo-w ./test/data/nowrite
    - chmod ugo-r ./test/data/noread

script:
    - npm run lint
    - npm test

after_success:
    - npm install istanbul codecov
    - chmod ugo+r ./test/data/noread
    - npm run coverage
    - ./node_modules/.bin/codecov

sudo: false
